### ISSUE TITLE
customizable text on the assignment-request pages

### ISSUE THREAD

**Issue by padili** [juntagrico/juntagrico-assignment-request#10]
same as for juntagrico is, to have customizable textes for the pages.
https://github.com/juntagrico/juntagrico/issues/411

i know it as text conserve in the DB, the text_area has a name and every language/local has its column. (or text_area, local, text)
eg one table per app  (eg juntagrico_assignment_request_vocabulary) or one table per entity (for juntagrico) to not have all in one big table.
what would be the preferred approach to handle this feature?

![image](https://user-images.githubusercontent.com/25586157/142880004-9b87440b-97c2-43ac-b9f0-1a08fb0d0ca3.png)

the assignment request is a nice little app to try it out 😄

**Comment by padili** [comment]
@pascalfree 
would it be ok for you if we go for the following text with the next release (before having the conserve):
_Hier kannst du deine Arbeitseinsätze melden. Dies gilt für Termine, die nicht mit einer festgelegten Arbeitszeit buchbar sind aber auch für selbständige Einsätze.Bitte sprich dich vorgängig mit einer Gartenfachkraft oder einer/m Arbeitsgruppen-KoordinatorIn ab, wenn du selbständige Einsätze machen willst._

**Comment by pascalfree** [comment]
Yes let's keep it simple for now.
That text would work for us as well for now.
