### ISSUE TITLE
enable app for python 3.9

### ISSUE THREAD

**Issue by padili** [juntagrico/juntagrico-assignment-request#5]
there are hardcoded paths to python 3.8 directories. 
its useful to have it inline with juntagrico to not get stucked in the python version and so in the version of juntagrico

**Comment by pascalfree** [comment]
Where are these hardcoded paths?

**Comment by padili** [comment]
as i recreated my docker image, it seems to work now.
could have been a problem with my volumes 👍 
i will close this issue 😃
