### ISSUE TITLE
create assigments with HOURS or ENTITY, depending on the setting ASSIGNEMENT_UNIT of juntagrico

### ISSUE THREAD

**Issue by padili** [juntagrico/juntagrico-assignment-request#6]
At the moment the assignment is created with the given entities

It would be great to use the ASSIGNMENT_UNIT to decide if it is the entity or the hours resp. entity * hours to create the assignment.

**Comment by padili** [comment]
in progress ... could take a while ... as i'm learning a lot at the moment 😄

**Comment by pascalfree** [comment]
I assume it is enough to show "hours" in the "amount" field of the assignment request form, depending on the setting. Right?

**Comment by padili** [comment]
it depends how it is used at the moment. I would suggest to not lose functionality we could show both?
like this you can request 4 times 2h for driving to the depots 🤔 
what do you think @pascalfree ?

**Comment by padili** [comment]
there was one more issue coming up that i have to create 🙈 
to have DecimalField for the duration
in the assignment this is already standard
but not for the duration in the assignment_request

**Comment by pascalfree** [comment]
Just found that there is the "duration in hours" field.
I think if we keep both fields and multiply in the background, the help text of the amont field should explain that these are multiplied, as it isn't obvious. And that is only for the case that HOURS are used.
Also the hours must then be shown (ideally editable) on the confirmation form.

I agree with the decimals on the duration. This has been changed in juntagrico 1.4

**Comment by padili** [comment]
perfect. 
I'll consider your inputs. 
Thanks a lot!

**Comment by padili** [comment]
i see, as the help_text is in the Migration, its not so easy to depend on the settings 🤔 
and at the moment the "Duration in Hours"  is not used to create the assignment?
to i get this two points correctly?
can one see on how many installation an app is used?
Sorry my silly questions 🙈

**Comment by pascalfree** [comment]
I think the help_text in the migration is not relevant (only the one in the entity). I don't know why django includes that in the migration, as I think it is not stored in the database.

Yes, at the moment the duration is not used. It should be multiplied here if the assignment unit is HOURS:
https://github.com/juntagrico/juntagrico-assignment-request/blob/69eee30523839a3809b7ce437d12333e86a7138d/juntagrico_assignment_request/entity/assignment_request.py#L141

To my knowledge we two are the only ones using this extension at the moment.

**Comment by padili** [comment]
this is the part i added it ... 
I also found the forms where to add the field in the confirm form 💪 
but there is another challenge i found, when i update a confirmed assignment request in the admin tool it updates the assignment with the assignment_request.amount ... i will find the solution 😋

**Comment by padili** [comment]
@pascalfree if it is OK for you >> for us we can wait with the release until i fixed this issue and #7 
i like to implement a nice solution and also (as i am a tester) try to implement some tests for the feature 😄 
as i can learn really a lot with this small things 😆

**Comment by pascalfree** [comment]
> 
> 
> this is the part i added it ... I also found the forms where to add the field in the confirm form 💪 but there is another challenge i found, when i update a confirmed assignment request in the admin tool it updates the assignment with the assignment_request.amount ... i will find the solution 😋

If you multiply in the line I linked, it should work via admin as well, as this is triggered when saving the request (from anywhere). But that's only the theory.

**Comment by padili** [comment]
the theory is correct for creating a new one, but not for updating 😋 
then it is the upper part and here i have to figure out how the objects in python are working 💪 
i already found out how it is not working 🤣 
https://github.com/juntagrico/juntagrico-assignment-request/blob/69eee30523839a3809b7ce437d12333e86a7138d/juntagrico_assignment_request/entity/assignment_request.py#L132
instance.assignment.amount is some how not the right one but I will learn, just no more today 😄

**Comment by pascalfree** [comment]
You are right.
Found it:
https://github.com/juntagrico/juntagrico-assignment-request/blob/69eee30523839a3809b7ce437d12333e86a7138d/juntagrico_assignment_request/models.py#L44

You'll want to make a method `get_amount()` or similar on the assignment request that you can reuse, similar to `get_matching_job()`

good night :-)

**Comment by padili** [comment]
@pascalfree as discussed with stackholders, we like to use the amount x duration approach, as it is quite often that we enter multiple jobs.

**Comment by padili** [comment]
@pascalfree , i skip the tests for now. its not so easy to get into this, how it is to implement. 
When i getting bigger i will manage 🤣 i have to learn much more about the packages and applications.

**Comment by padili** [comment]
@pascalfree, One thing i have to ask about the implementation. How can I prevent a 'NullPointerException', if the config ASSIGNMENT_UNIT does not exist?

**Comment by pascalfree** [comment]
The config value should default to entity if it isn't set, I think. 
Can you paste the trace back of the error?

**Comment by padili** [comment]
Your right 😄 no error happened. I was just thinking ahead to prevent NPEs 👍
